Websocket improvements
tibber/com.tibber.athom pull request #50
Opened 2022-10-14 14:06 UTC by toini

2022-10-17 18:06 UTC, jstaro requested changes
Looks good! Just some tiny naming suggestions and removing some commented-out code.

2022-10-17 18:06 UTC, jstaro commented on drivers/pulse/device.ts
> +    let {
```suggestion
    const {
```

2022-10-17 18:06 UTC, jstaro commented on drivers/watty/device.ts
> +    this.#resubscribeMaxWait = (jitter + delay) * 1000; // Milliseconds
Naming: same deal as in `pulse/device.ts`

2022-10-17 18:06 UTC, jstaro commented on drivers/watty/device.ts
> +    let {
```suggestion
    const {
```

2022-10-17 18:06 UTC, jstaro commented on lib/tibber.ts
> +      // },
Remove.

2022-10-18 07:43 UTC, toini commented on lib/tibber.ts
> +      // },
Im still testing this part. Turned out atm server doesnt close the connection when it shutsdown. I'll try to make it do that (node18 even has a new function for closing all http server connections). I believe we should arrive in this method when server closes with fatal http status.

2022-10-18 07:44 UTC, toini commented on drivers/pulse/device.ts
> +    let {
But websocketSubscriptionUrl needs to be a variable as it gets updated, right?

2022-10-18 11:09 UTC, toini commented on lib/tibber.ts
> +      // },
No need for node18. serverCleanup.dispose() does the trick. Just needed to add a temporary endpoint for calling that (when running in debugger it seems to die without any dispose - would need to test this on server too).

2022-10-18 11:11 UTC, toini commented on drivers/watty/device.ts
> +    let {
websocketSubscriptionUrl needs to be variable.

2022-10-18 11:21 UTC, merged

2022-10-18 21:11 UTC, jstaro commented on drivers/pulse/device.ts
> +    let {
Ah, right. Couldn't compile that code in my head, sorry.